# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precendence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by defaul the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
server:
  port: 8083

security:
  basic:
    enabled: "${SECURITY_ENABLED:true}"
  user:
    name: "admin"
    password: "admin"

logging:
  level:
    org:
      opentestsystem:
        ap:
          irs: "debug"
          common: "debug"

spring:
  session:
    enabled: "${SESSION_CLUSTER_ENABLED:true}"

itembank:
  host: "https://gitlab-dev.smarterbalanced.org"
  accessToken: "${GITLAB_ACCESS_TOKEN}"
  user: "${GITLAB_USER}"
  password: "${GITLAB_PASSWORD}"
  group: "${GITLAB_GROUP}"
  localBaseDir: "${HOME}/ItemBankIVS"
  apiVersion: "/api/v4"
  bankKey: "187"
  systemVersion: "iat-6"

ivs:
  host: "${IVS_HOST:http://localhost:8200}"
  externalHost: "${IVS_HOST:http://localhost:8200}"
  ivsBaseDir: "${IVS_BASE_DIR:${HOME}/ItemBankIVS}"

tasks:
  itemCleanupThresholdMillis : "1800000"
  itemCleanupRunEveryMillis: "1800000"
  ivsItemCleanupThresholdMillis : "1800000"
  ivsItemCleanupRunEveryMillis: "1800000"

---
spring:
  profiles: dev

itembank:
  group: "iat-development"