# ---------------------------------------------------------
# The Gradle build expands its project properties to
# replace the substitution tokens.
# ---------------------------------------------------------

# shown on the actuator /info endpoint
info:
  app:
    name: ${name}
    version: ${version}
    description: ${description}
    java:
      source: ${sourceCompatibility}
      target: ${targetCompatibility}

# changes actuator endpoints - /manage/info
management:
  context-path: "/manage"

api:
  context-path: "/api"

security:
  basic:
    enabled: \${SECURITY_ENABLED:true}

spring:
  session:
    enabled: \${SESSION_CLUSTER_ENABLED:true}
  datasource:
    url: "jdbc:postgresql://localhost:5432/iat"
    username: \${DB_USER}
    password: \${DB_PASSWORD}
    validationQuery: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

itembank:
  systemVersion: "iat-41"
  localBaseDir: \${HOME}/ItemBankIVS
  systemUser:
    userName: "iat-item-rendering-service@smarterbalanced.org"
    fullName: "Item Rendering Service"
  enabled:
    database: true
  services:
    history:
      url: "http://localhost:8086"
  aws:
    endpointUrl: "https://s3.us-east-2.amazonaws.com"
    region: "us-east-2"
    bucketName: \${GITLAB_GROUP}
    versionedBucketName: \${GITLAB_GROUP}-versioned
    accessKey: \${IAT_AWS_ACCESS_KEY}
    secretKey: \${IAT_AWS_ACCESS_SECRET}
  preview:
    host: \${IVS_HOST:/iatpreview}
    externalHost: \${IVS_HOST:/iatpreview}
    ivsBaseDir: \${IVS_BASE_DIR:\${HOME}/ItemBankIVS}

tasks:
  itemCleanupThresholdMillis : "1800000000"
  itemCleanupRunEveryMillis: "1800000000"