version: '2.1'
services:
    redis-server:
      container_name: redis-server
      image: healthcheck/redis
      networks:
        - spring-cloud-network
      ports:
        - 6379:6379
      logging:
        driver: json-file
    config-server:
      container_name: config-server
      image: fwsbac/configuration-service:@configServerVersion@
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
        interval: 30s
        timeout: 5s
        retries: 3
      environment:
        CONFIG_SERVICE_REPO: "file://tmp"
      expose:
          - 8888
      ports:
          - 8888:8888
      networks:
          - spring-cloud-network
      volumes:
          - @USER_HOME@/smarter_app/iat-config-repo:/tmp
      logging:
          driver: json-file
    ap-irs:
        container_name: ap-irs
        image: fwsbac/ap-irs:@version@
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8080/manage/health"]
          interval: 30s
          timeout: 5s
          retries: 3
        environment:
            CONFIG_SERVICE_ENABLED: "true"
            CONFIG_SERVICE_URL: "http://config-server:8888"
            SPRING_PROFILES_ACTIVE: "localcompose"
        ports:
            - 8083:8080
        networks:
            - spring-cloud-network
        links:
            - config-server
        depends_on:
          config-server:
            condition: service_started
        volumes:
            - @USER_HOME@/smarter_app:/tmp
        logging:
            driver: json-file
networks:
    spring-cloud-network:
        driver: bridge
