version: '2.1'
services:
    ivs-service:
        container_name: ivs-service
        image: osucass/itemviewerserviceapp:1.1.3
        expose:
            - 8080
        ports:
            - 8200:8080
        networks:
            - spring-cloud-network
        volumes:
            - ${HOME}/ItemBankIVS/:/home/tomcat7/content/
        logging:
            driver: json-file
networks:
    spring-cloud-network:
        driver: bridge