version: '2.1'
services:
    # iris-service:
    #     container_name: iris-service
    #     image: osucass/tds_irisapp:2.0.0
    #     expose:
    #         - 8080
    #     ports:
    #         - 8080:8080
    #     networks:
    #         - spring-cloud-network
    #     volumes:
    #         - /Users/alexponce/smarter_app/sbac-config-repo:/tmp
    #     logging:
    #         driver: json-file
    ivs-service:
        container_name: ivs-service
        image: osucass/itemviewerserviceapp:1.1.3
        expose:
            - 8080
        ports:
            - 8200:8080
        networks:
            - spring-cloud-network
        # links:
        #     - iris-service
        # depends_on:
        #   iris-service:
        #     condition: service_started
        volumes:
            - /opt/iris/data/:/home/tomcat7/content/
        logging:
            driver: json-file
networks:
    spring-cloud-network:
        driver: bridge